#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2023.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Dec 21 07:42:58 CET 2023
# SW Build 3865809 on Sun May  7 15:04:56 MDT 2023
#
# IP Build 3864474 on Sun May  7 20:36:21 MDT 2023
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_proc_behav -key {Behavioral:sim_1:Functional:tb_proc} -tclbatch tb_proc.tcl -view /home/gnanguessim/Bureau/VHDL_CIRCUIT_NUM/proc_v1/proc_v1.srcs/sim_1/imports/proc_v1/tb_proc_behav.wcfg -log simulate.log"
xsim tb_proc_behav -key {Behavioral:sim_1:Functional:tb_proc} -tclbatch tb_proc.tcl -view /home/gnanguessim/Bureau/VHDL_CIRCUIT_NUM/proc_v1/proc_v1.srcs/sim_1/imports/proc_v1/tb_proc_behav.wcfg -log simulate.log

